<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260114193352 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE country (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tax (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount DOUBLE PRECISION NOT NULL, country_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8E81BA76F92F3E70 ON tax (country_id)');
        $this->addSql('CREATE TABLE tax_number (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pattern VARCHAR(255) NOT NULL, tax_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DA4A75FFB2A824D8 ON tax_number (tax_id)');
        $this->addSql('ALTER TABLE tax ADD CONSTRAINT FK_8E81BA76F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tax_number ADD CONSTRAINT FK_DA4A75FFB2A824D8 FOREIGN KEY (tax_id) REFERENCES tax (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tax DROP CONSTRAINT FK_8E81BA76F92F3E70');
        $this->addSql('ALTER TABLE tax_number DROP CONSTRAINT FK_DA4A75FFB2A824D8');
        $this->addSql('DROP TABLE country');
        $this->addSql('DROP TABLE tax');
        $this->addSql('DROP TABLE tax_number');
    }
}
